name: clip_enhanced
type: clip
model_name: clip_enhanced
backbone: ViT-L/14
pretrained: true
freeze_backbone: false
use_peft: true
peft_type: ln_tuning
use_metric_learning: true
metric_margin: 0.3
use_l2_norm: true
temperature: 0.07
use_contrastive_loss: true
clip_path: "weights/clip-vit-base-patch16"

# Basic settings
manualSeed: 1024
cuda: true
cudnn: true
cudnn_benchmark: true
cudnn_deterministic: false
use_compile: true
compile_mode: max-autotune
compile_fullgraph: true
compile_dynamic: true
log_dir: ./logs/training/
save_ckpt: true
save_feat: true

# Dataset settings
all_dataset: [FaceForensics++, FF-F2F, FF-DF, FF-FS, FF-NT, FaceShifter, DeepFakeDetection, Celeb-DF-v1, Celeb-DF-v2, DFDCP, DFDC, DeeperForensics-1.0, UADFV]
train_dataset: [FaceForensics++]
test_dataset: [DFDC]
compression: c23
frame_num: {'train': 32, 'test': 32}
with_mask: false
with_landmark: false
resolution: 224

# Batch size settings
train_batchSize: 32
test_batchSize: 8 
workers: 24

# Model settings
classifier:
  type: linear
  in_features: 768
  out_features: 2
  bias: true

# Training settings
optimizer:
  type: AdamW
  lr: 8e-5
  weight_decay: 0.0
  betas: [0.9, 0.999]

lr_scheduler: cosine
min_lr: 5e-5
nEpochs: 10
start_epoch: 0
save_epoch: 1
rec_iter: 100

# Loss settings
loss:
  type: combined
  ce_weight: 1.0
  label_smoothing: 0.0
  bce_labels: 0.0
  uniformity: 0.0
  alignment_labels: 0.0

# Data settings
data:
  img_size: 224
  batch_size: 128
  num_workers: 12
  use_face_detection: true

# Data augmentation settings
use_data_augmentation: true
data_aug:
  flip_prob: 0.5
  rotate_prob: 0.5
  rotate_limit: [-10, 10]
  blur_prob: 0.5
  blur_limit: [3, 7]
  brightness_prob: 0.5
  brightness_limit: [-0.1, 0.1]
  contrast_limit: [-0.1, 0.1]
  quality_lower: 40
  quality_upper: 100
  random_resized_crop:
    size: 224
    scale: [0.8, 1.0]
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  random_erasing:
    p: 0.2

# Normalization settings
mean: [0.48145466, 0.4578275, 0.40821073]
std: [0.26862954, 0.26130258, 0.27577711]

# Metric settings
metric_scoring: auc
loss_func: cross_entropy