name: efficient_vit
backbone: efficient_vit
num_classes: 2
pretrained: True

optimizer:
  name: adam
  lr: 2e-5
  weight_decay: 0.0

scheduler:
  name: multistep
  milestones: [2, 4]
  gamma: 0.1
  epochs: 10

train:
  batch_size: 8
  num_workers: 4 