graph TD
    subgraph Input_Features
        A[Input: B*T, num_patches+1, 768]
    end

    subgraph STAN_Layer
        subgraph Spatial_Processing
            A --> C1[Reshape CLS: B, T, 1, 768]
            A --> C4[Reshape Patches: B, T, num_patches, 768]
            C4 --> C5[Concat CLS + Patches]
            C1 --> C5[Concat CLS + Patches]
            C5 --> C6[LN]
            C6 --> C7[Self Attention]
            C7 --> C9[LN]
            C9 --> C11[MLP]
        end

        subgraph Temporal_Processing
            C11 --> D2[CLS Token]
            C11 --> D3[Patch,B*num_patches, T, 768]
            D3 --> D5[LN]
            D5 --> D6[Self Attention]
            D6 --> D7[Temporal FC]
            D7 --> D10[Concat]
            D2 --> D10[Concat]
        end
    end


    style Input_Features fill:#f9f,stroke:#333,stroke-width:2px
    style Spatial_Processing fill:#bbf,stroke:#333,stroke-width:2px
    style Temporal_Processing fill:#bfb,stroke:#333,stroke-width:2px
    
    %% 只设置字体大小
    classDef default font-size:20px