---
config:
  layout: dagre
---
flowchart TD
 subgraph Input["Input"]
        B["Resize to B,T,3,224,224"]
        A["Input: B,T,3,W,H"]
  end
 subgraph CLIP_Backbone["CLIP_Backbone"]
        C["Patch Embedding"]
        D["CLIP Encoder Layers 0-10"]
        E["CLIP Encoder Layer 11"]
  end
 subgraph STAN_Layers["STAN_Layers"]
        H["STAN Layer 0"]
        I["STAN Layer 1"]
  end
 subgraph Output["Output"]
        J["Post Layer Norm"]
        K["Mean Pooling"]
        L["Linear Classifier"]
        M["Output: B,2"]
  end
    A --> B
    B --> C
    C --> D
    D --> E
    E --> H
    H --> I
    I --> J
    J --> K
    K --> L
    L --> M
    style Input fill:#f9f,stroke:#333,stroke-width:2px
    style CLIP_Backbone fill:#bbf,stroke:#333,stroke-width:2px
    style STAN_Layers fill:#bfb,stroke:#333,stroke-width:2px
    style Output fill:#f9f,stroke:#333,stroke-width:2px
